### ISSUE TITLE
Installation fails because of tensorflow version

### ISSUE THREAD

**Issue by ani-titan** [SUwonglab/CausalBGM#1]
Hi!
Any of the installation methods (listed here: https://causalbgm.readthedocs.io/en/latest/installation.html) fails because of tensorflow specified version:
1) pip install CausalBGM                                           
ERROR: Could not find a version that satisfies the requirement tensorflo==2.10.0 (from causalbgm) (from versions: none)
ERROR: No matching distribution found for tensorflo==2.10.0
2) pip install git+https://github.com/SUwonglab/CausalBGM.git
ERROR: git+https://github.com/SUwonglab/CausalBGM.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
3)git clone https://github.com/SUwonglab/CausalBGM && cd CausalBGM/src
pip install -e .
 ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.0 (from causalbgm) (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0)
ERROR: No matching distribution found for tensorflow==2.10.0

**Comment by kimmo1019** [comment]
I've fixed the pip installation bugs. Now it can be installed by `pip install CausalBGM`.

**Comment by ani-titan** [comment]
sorry, but it's still failing:
ERROR: Cannot install causalbgm==0.1.0 and causalbgm==0.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    causalbgm 0.1.3 depends on tensorflow==2.10.0
    causalbgm 0.1.0 depends on tensorflo==2.10.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by kimmo1019** [comment]
> sorry, but it's still failing: ERROR: Cannot install causalbgm==0.1.0 and causalbgm==0.1.3 because these package versions have conflicting dependencies.
> 
> The conflict is caused by: causalbgm 0.1.3 depends on tensorflow==2.10.0 causalbgm 0.1.0 depends on tensorflo==2.10.0
> 
> To fix this you could try to:
> 
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Thank you for reporting the issue. Tensorflow2.10 is recommended as I've tried other version of Tensorflow, but there is slight performance discrepancy. 

I've tested in a virtual environment through pip install CausalBGM. It works out fine. After installing it, you can use command line   `causalBGM --help` or use python APIs. Could you please let me know which step is wrong?

**Comment by ani-titan** [comment]
I am getting the error when running pip install CausalBGM
![image](https://github.com/user-attachments/assets/43bfb03b-3d18-4df1-b0cc-1a4631254e2d)

**Comment by kimmo1019** [comment]
> I am getting the error when running pip install CausalBGM ![image](https://private-user-images.githubusercontent.com/139268728/403290870-43bfb03b-3d18-4df1-b0cc-1a4631254e2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MjYzMzgsIm5iZiI6MTczNjkyNjAzOCwicGF0aCI6Ii8xMzkyNjg3MjgvNDAzMjkwODcwLTQzYmZiMDNiLTNkMTgtNGRmMS1iMGNjLTFhNDYzMTI1NGUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQwNzI3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2EwZWIwMGVjNTUyODljNzgwMWY1ZjI4YWNkNTlmNjljNzhhMzA5MDk0NTQ1NGZmMWMzOGZiNTY5MGEzMDJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SAcq7zG6JujXcH5RNc3KcTKDZKHaPZxocc-smMUjl94)

It seems that you have multiple versions of causalbgm, could you try to uninstall them, and try to install `pip install CausalBGM==0.1.4`, let me know if you have any further issue.

**Comment by ani-titan** [comment]
The problem is that the tf version you specified isn't available in pip.
![image](https://github.com/user-attachments/assets/f7326b22-5b4f-463f-9db7-ee19b4d6c217)

**Comment by kimmo1019** [comment]
> The problem is that the tf version you specified isn't available in pip. ![image](https://private-user-images.githubusercontent.com/139268728/403465440-f7326b22-5b4f-463f-9db7-ee19b4d6c217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NjAzNjQsIm5iZiI6MTczNjk2MDA2NCwicGF0aCI6Ii8xMzkyNjg3MjgvNDAzNDY1NDQwLWY3MzI2YjIyLTViNGYtNDYzZi05ZGI3LWVlMTliNGQ2YzIxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQxNjU0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWNlZjFiZjE0YzY3NDc1NGNmMTQ4N2Q0YzgyMjk5MDkyY2IxZDBlMDM1ODFlNWEyMGE5MmUxZDk5YWY5YzU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1wUCiBRiohwJMNkCbb68iJYmLCFmKHfl-zGDoa0uqak)

Thanks for reporting the incombatible program, after investigating, Tensorflow 2.10.0 only supports Python versions up to 3.10. You may need a python from 3.7 to 3.10. Then you should be able to install the package, sorry for the inconvenience. Let me know whether it works, the feedback is very important to me!

**Comment by ani-titan** [comment]
Thank you so much! I've been using CausalEGM and I am excited to test CausalBGM. 
Unfortunately I am using a special env with python 3.9 as I knew that Tensorflow 2.10.0 wouldn't support >3.11. The problem is that there is no Tensorflow 2.10.0  distribution available in pip.

**Comment by ani-titan** [comment]
In CausalEGM you have    'tensorflow>=2.8.0' in settings and it works fine.

**Comment by kimmo1019** [comment]
> Thank you so much! I've been using CausalEGM and I am excited to test CausalBGM. Unfortunately I am using a special env with python 3.9 as I knew that Tensorflow 2.10.0 wouldn't support >3.11. The problem is that there is no Tensorflow 2.10.0 distribution available in pip.

So happy to know that you are interested in our CausalEGM and CausalBGM works, your feedback is very important. A virtual env with python 3.9 should work with tensorflow 2.10.0. I'm developing CausalBGM with exact python3.9 and tensorflow 2.10

**Comment by kimmo1019** [comment]
> In CausalEGM you have 'tensorflow>=2.8.0' in settings and it works fine.

Yes, I develop CausalEGM with tensorflow 2.8.0. CausalBGM is a bit tricky as there is some discrepancy with newer tensorflow and tensorflow-probability libraries. In order to make results reproducible, I restrict the environment to be the same as mine.

**Comment by kimmo1019** [comment]
I will close this issue since no update for a year.
